### ISSUE TITLE
Fedora 30

### ISSUE THREAD

**Issue by taaem** [abn/throttled-rpm#1]
It would be nice if you could enable builds for Fedora 30 in the copr repo so users of the new release get it by day one.

**Comment by MiguelDeLillo** [comment]
I would really like to use this as soon as possible on my Fedora 30 T480s, currently running the beta. Please, do this!

**Comment by inffy** [comment]
This one has F30 support: http://copr.fedorainfracloud.org/coprs/ramonmaruko/throttled/
