### ISSUE TITLE
throttled service failed to start.

### ISSUE THREAD

**Issue by aneeshrb** [abn/throttled-rpm#11]
I'm using ThinkPad T480 Fedora 30 Kernel 5.3.16-200. When i'm starting the throttled service it's failed.throttled.service - Stop Intel throttling

systemctl status throttled
● throttled.service - Stop Intel throttling
   Loaded: loaded (/usr/lib/systemd/system/throttled.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-01-01 21:39:42 IST; 12min ago
  Process: 6086 ExecStart=/usr/bin/throttled --config /etc/throttled.conf (code=exited, status=1/FAILURE)
 Main PID: 6086 (code=exited, status=1/FAILURE)

Jan 01 21:39:41 localhost.localdomain systemd[1]: Started Stop Intel throttling.
Jan 01 21:39:42 localhost.localdomain throttled[6086]: [I] Detected CPU architecture: Intel Kaby Lake (R)
Jan 01 21:39:42 localhost.localdomain throttled[6086]: [I] Loading config file.
Jan 01 21:39:42 localhost.localdomain throttled[6086]: [E] Unable to write to MSR. Try to disable Secure Boot and check if your kernel does not restrict acce>
Jan 01 21:39:42 localhost.localdomain throttled[6086]: [E] Unable to open /dev/mem. Try to disable Secure Boot.
Jan 01 21:39:42 localhost.localdomain systemd[1]: throttled.service: Main process exited, code=exited, status=1/FAILURE
Jan 01 21:39:42 localhost.localdomain systemd[1]: throttled.service: Failed with result 'exit-code'.

**Comment by abn** [comment]
@aneeshrb this is not a packaging issue as far as I can tell. The following snippet seems to indicate that somehting is blocking required access:
```
Jan 01 21:39:42 localhost.localdomain throttled[6086]: [E] Unable to write to MSR. Try to disable Secure Boot and check if your kernel does not restrict acce>
Jan 01 21:39:42 localhost.localdomain throttled[6086]: [E] Unable to open /dev/mem. Try to disable Secure Boot.
```

You could try as suggested or try upgrading to `0.7`.
