### ISSUE TITLE
Tag for Fedora 33 but missing on copr

### ISSUE THREAD

**Issue by elwerene** [abn/throttled-rpm#12]
You might have forgotten to push the build to copr as it still missing [there](https://copr-be.cloud.fedoraproject.org/results/abn/throttled/fedora-33-x86_64/).

Thanks @abn for maintaining a rpm package of throttled for Fedora :+1:

**Comment by jallentc** [comment]
Same.  Still unable to a pull the package from the copr repo:

`[user@box lenovo-throttling-fix]$ sudo dnf install -y throttled`
`Copr repo for throttled owned by abn                                                                                                                          8.4 kB/s | 3.3 kB     00:00`    
`No match for argument: throttled`
`Error: Unable to find a match: throttled`

>

**Comment by abn** [comment]
Apologies for missing this, will get this bumped to 0.8. I also need to switch to github actions, so might take a couple of days before I get this published.

**Comment by abn** [comment]
Turned out to be easier than anticipated. The new tag seems to have been built for fedora 33. Let me know if that did not work.

https://download.copr.fedorainfracloud.org/results/abn/throttled/fedora-33-x86_64/01816110-throttled/

**Comment by Obihoernchen** [comment]
@abn There is a dependency issue. This tool runs with python 3 (3.9 for Fedora 33) and should not need `python3-configparser`. This package is not available anymore in Fedora 33.
```
# dnf install -y throttled
Error: 
 Problem: conflicting requests
  - nothing provides python3-configparser needed by throttled-0.8-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by abn** [comment]
@Obihoernchen I just caught that; waiting for the 0.8-2 build to finish. :) Forgot fedora 33 dropped that pakcage since python2 no longer exists and that was a backports package.

**Comment by Obihoernchen** [comment]
But so far it works as expected with skipped dependencies:
```
# wget https://download.copr.fedorainfracloud.org/results/abn/throttled/fedora-33-x86_64/01816110-throttled/throttled-0.8-1.x86_64.rpm
# rpm -Ivh --nodeps throttled-0.8-1.x86_64.rpm
[root@t470-obi tmp]# systemctl status throttled
● throttled.service - Stop Intel throttling
     Loaded: loaded (/usr/lib/systemd/system/throttled.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2020-12-06 01:29:22 CET; 1min 21s ago
   Main PID: 170034 (throttled)
      Tasks: 2 (limit: 18852)
     Memory: 11.9M
        CPU: 115ms
     CGroup: /system.slice/throttled.service
             └─170034 /usr/bin/python3 /usr/bin/throttled --config /etc/throttled.conf

Dez 06 01:29:22 systemd[1]: Started Stop Intel throttling.
Dez 06 01:29:22 throttled[170034]: [I] Detected CPU architecture: Intel Kaby Lake (R)
Dez 06 01:29:22 throttled[170034]: [I] Loading config file.
Dez 06 01:29:22 throttled[170034]: [I] Starting main loop.
```

**Comment by abn** [comment]
@Obihoernchen thank you for testing it, much appreciated. The new release is now ready too.

**Comment by Obihoernchen** [comment]
`throttled-0.8-2.x86_64` works :+1:

**Comment by elwerene** [comment]
Nice work! Thank you very much @abn!

**Comment by jallentc** [comment]
Thanks @abn I can also confirm that I was able to install `throttled-0.8-2.x86_64` from the copr repo, and throttled is now up and running again!  Great work and many thanks!
