### ISSUE TITLE
user/group throttled does not exist

### ISSUE THREAD

**Issue by mstsirkin** [abn/throttled-rpm#2]
I get this during install:

warning: user throttled does not exist - using root
warning: group throttled does not exist - using root

I guess these should be created?
And I guess selinux labels need to be applied in some way too?

**Comment by abn** [comment]
@mstsirkin thanks for reporting this. Will get it fixed.

**Comment by jdloft** [comment]
Is there any reason this has not been merged? There are a ton of different versions on Fedora's COPR with and without this fix.
