### ISSUE TITLE
Asking for a rebuild - TigerLake and Alder Lake support

### ISSUE THREAD

**Issue by lakotamm** [abn/throttled-rpm#21]
Hello!
Could I ask for a rebuild? In the last commits there has beeen a lot of work done on TigerLake and AlderLake support.
https://github.com/erpalma/throttled/commit/77eb1ac080ae99e8a04ce07f425ecda125ecb911 https://github.com/erpalma/throttled/commit/cc5948b6f43ba0a44b90389e15eb58c9bceb75c6

Thank you!

**Comment by abn** [comment]
Resolved with https://github.com/abn/throttled-rpm/commit/0741a05b1dc240099c683a535c9ea6567ef8b47c (hopefully).
