### ISSUE TITLE
The mandatory "Update_Rate_s" parameter is missing.

### ISSUE THREAD

**Issue by mmrezaie** [abn/throttled-rpm#4]
By running:     sudo ./lenovo_fix.py --monitor
I get this output:

[I] Detected CPU architecture: Intel Kaby Lake (R)
[I] Loading config file.
[E] The mandatory "Update_Rate_s" parameter is missing.

I am running Fedora 30, Kernel 5.2.6, and Thinkpad X1. I have installed throttled using the Copr repository (in case it is important information).

**Comment by halfpastfive** [comment]
I have the same issue. As a workaround, running with : 

`sudo throttled --config /etc/throttled.conf --monitor`

(using the version from the copr repository).

**Comment by mmrezaie** [comment]
Thanks. This works.
