### ISSUE TITLE
Fedora 31 builds?

### ISSUE THREAD

**Issue by aenertia** [abn/throttled-rpm#5]
Can we get the 31 builds in the copr now it's tagged?

Also building manually  on the current 31 userspace fails:

> 
> >  ERROR: Complete output from command /opt/lenovo_fix/venv/bin/python3 /opt/lenovo_fix/venv/lib64/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-bqivol2g/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo:                      
>   ERROR: Collecting setuptools
>     Downloading https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl (576kB)                                                                 
>   Collecting wheel                                                                                                   
>     Downloading https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl                                                                              
>   Collecting pycairo                                                                                                 
>     Downloading https://files.pythonhosted.org/packages/48/20/5e83af98eb897935bf7dc39455e892ba866feebb9b7c3b392982866f9958/pycairo-1.18.1.tar.gz (200kB)                                                                                  
>   Installing collected packages: setuptools, wheel, pycairo                                                          
>     Running setup.py install for pycairo: started                                                                    
>       Running setup.py install for pycairo: finished with status 'error'                                             
>       ERROR: Complete output from command /opt/lenovo_fix/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-xw8kzhcs/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-959dad4p/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-bqivol2g/overlay --compile --install-headers /opt/lenovo_fix/venv/include/site/python3.7/pycairo:                              
>       ERROR: running install                                                                                         
>       running build                                                                                                  
>       running build_py                                                                                               
>       creating build                                                                                                 
>       creating build/lib.linux-x86_64-3.7                                                                            
>       creating build/lib.linux-x86_64-3.7/cairo                                                                      
>       copying cairo/__init__.py -> build/lib.linux-x86_64-3.7/cairo                                                  
>       copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.7/cairo                                                 
>       copying cairo/py.typed -> build/lib.linux-x86_64-3.7/cairo                                                     
>       running build_ext                                                                                              
>       Package cairo was not found in the pkg-config search path.                                                     
>       Perhaps you should add the directory containing `cairo.pc'                                                     
>       to the PKG_CONFIG_PATH environment variable                                                                    
>       Package 'cairo', required by 'virtual:world', not found                                                        
>       Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.     
> 
> > 
> >       ----------------------------------------                                                                       
> >   ERROR: Command "/opt/lenovo_fix/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-xw8kzhcs/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-959dad4p/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-bqivol2g/overlay --compile --install-headers /opt/lenovo_fix/venv/include/site/python3.7/pycairo" failed with error code 1 in /tmp/pip-install-xw8kzhcs/pycairo/                                                                                                            
> >   WARNING: You are using pip version 19.1.1, however version 19.2.3 is available.                                    
> >   You should consider upgrading via the 'pip install --upgrade pip' command.                                         
> >   ----------------------------------------                                                                           
> > ERROR: Command "/opt/lenovo_fix/venv/bin/python3 /opt/lenovo_fix/venv/lib64/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-bqivol2g/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo" failed with error code 1 in None           
> > WARNING: You are using pip version 19.1.1, however version

**Comment by BjoernDaase** [comment]
@aenertia Why was this closed? I still see no F31 builds...
